all:
	git add .
	git commit -m "commit all changes"
	git push origin HEAD

mf:
	git add .\Makefile
	git commit -m "edit Makefile"
	git push origin HEAD

kali:
	git add .\kali_linux.md
	git commit -m "postscript"
	git push origin HEAD

